### PR TITLE
KITE-1102: Correct URI pattern registrations for s3a protocol

### PR DESCRIPTION
**Pull request by noslowerdna**
Minor change to fix https://issues.cloudera.org/browse/KITE-1102

### CODE REVIEW

**Comment by rdblue** [comment]
+1

I believe we left it as it was because we recommend S3N. Originally, we weren't sure whether the *path component would be useful to S3 users because buckets are available as an alternative.

**Comment by mkwhitacre** [comment]
+1

**Comment by mkwhitacre** [comment]
Can ignore the cdh4 profile failure b/c that is related to flume-ng download.  Rekicked off the default profile however as that seemed like a hung test.

**Comment by mkwhitacre** [comment]
Build successful aside from flaky cdh4 build.  merging.

**Pull request merged**
