### PR TITLE
KITE-1090: Set DefaultConfiguration during DatasetKeyInputFormat#load…

### PR DESCRIPTION
**Pull request by bbaugher**
…(..)

This fixed the [issue](https://issues.cloudera.org/browse/KITE-1090) for us

### CODE REVIEW

**Comment by bbaugher** [comment]
This change (https://github.com/bbaugher/kite/commit/80df91e2fd5baca65be76256f0e510d976aa6def) should fix the tests

**Comment by bbaugher** [comment]
Any idea why the cdh4 profile gets stuck?

**Comment by mkwhitacre** [comment]
+1 for the change.  

Also don't worry about the CDH4 being stuck.  @rdblue mentioned removing that Flume component and other pulls are having the same problem.

**Comment by rbrush** [comment]
+1; looks good to me. Any objections to merging this?

**Comment by mkwhitacre** [comment]
Didn't get any objections so merging.

**Pull request merged**
