### PR TITLE
CDK-1014: Fix support for Hive datasets on Kerberos enabled clusters.

### PR DESCRIPTION
**Pull request by joey**

### CODE REVIEW

**Comment by rdblue** [comment]
+1! (when tests pass)

Is there a way to test this?

**Comment by joey** [comment]
Ugh, this doesn't work with CDH4 due to API changes in Hive. Let me see what I can do.

**Comment by joey** [comment]
I still need to fix the CDH4 build. The latest patch add's support for Kerberos in the CopyCommand for Hive datasets. The fixes to the MR Input/OutputFormats isn't enough as you need to distribute a delegation token to the remote job.

I'm not sure we want that fix in this commit or not, but I figured I'd push it to show you what I had to do to test it.

**Comment by rdblue** [comment]
+1

Thanks, Joey!

**Comment by rdblue** [comment]
That was fast, I was just going to merge it. Thanks!

**Comment by joey** [comment]
Ha ha. I hope that was ok. I know historically we've merged our own branches, but I'm happy to have that move to the reviewer (I think that's what Hadoop does) if that makes sense.

**Comment by rdblue** [comment]
Merging our own branches is great. I just wanted to get this in as soon as possible. I'm going to need to backport it.

**Pull request merged**
