### PR TITLE
CDK-986. Allow partitioning on optional fields

### PR DESCRIPTION
**Pull request by tomwhite**

### CODE REVIEW

**Comment by rdblue** [comment]
+1

**Comment by joey** [comment]
Do we also have to define how the various partitioners handle a null value? For example, if I'm hash partitioned on a field what is the hash of a null value? Is it randomly assigned a partition or does it always go to a specific bucket?

The same kind of questions come up for other partitioners.

**Comment by rdblue** [comment]
I think the intent is to fail with NPE when partition values are null. We don't expect them to actually be null, but we don't want to be so strict about schemas.

**Comment by tomwhite** [comment]
That's right - if a partition value is actually null you'll get a NPE.

**Comment by tomwhite** [comment]
Merged in https://github.com/kite-sdk/kite/commit/3738dffc751cc8b26fceb0d4ce8445f23848bf57

**Pull request closed without merging**
