### PR TITLE
CDK-898: Use MRPipeline instead of MemPipeline

### PR DESCRIPTION
**Pull request by rdblue**
This is based on #303, but fixes the logging configuration so that a link to the MR job is given when running on a cluster and task errors are printed to the console when running locally.

### CODE REVIEW

**Comment by rdblue** [comment]
The last commit is a work-around for [CRUNCH-512](https://issues.apache.org/jira/browse/CRUNCH-512).

**Comment by tomwhite** [comment]
It looks like the last commit breaks tests. The other changes look good to me though.

**Comment by rdblue** [comment]
Fixed the tests. Changes to the configuration in the TransformTask were leaking into other test cases. The solution was to make a copy if it needs to make changes.

**Comment by rdblue** [comment]
Merged. Thanks for the review, Tom!

**Pull request merged**
